1:	dfsRecursive.o Graph.o
	gcc -Wall -Werror -o 1 dfsRecursive.o Graph.o
dfsRecursive.o:dfsRecursive.c Graph.h
	gcc -Wall -Werror -c dfsRecursive.c
Graph.o:Graph.c Graph.h
	gcc -Wall -Werror -c Graph.c

	
